networks:
  servers:

services:

  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    networks:
      - servers
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_interval: 5s
    depends_on:
      - db
    ports:
      - "8080:8080"

  server2:
    build: .
    networks:
      - servers
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_interval: 5s
    depends_on:
      - db
    ports:
      - "8081:8080"

  server3:
    build: .
    networks:
      - servers
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_interval: 5s
    depends_on:
      - db
    ports:
      - "8082:8080"

  db:
    build: .
    networks:
      - servers
    command: "db"
    ports:
      - "8432:8080"
    volumes:
      - db-data

volumes:
  db-data: